# Generated by Django 3.2.8 on 2022-08-06 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_bot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='bot',
            old_name='user_id',
            new_name='user',
        ),
    ]
