# Generated by Django 3.2.8 on 2022-09-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_bot_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='token',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
