# Generated by Django 3.2.8 on 2022-11-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0013_alter_player_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_expand',
            field=models.BooleanField(default=False),
        ),
    ]
