# Generated by Django 3.2.8 on 2022-11-11 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0014_player_is_expand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_expand',
        ),
    ]
