# Generated by Django 3.2.8 on 2022-11-13 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('player', '0016_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=300)),
                ('randomname', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('mimetype', models.CharField(max_length=50)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('url', models.URLField(blank=True, max_length=256)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_img', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
