# Generated by Django 3.2.8 on 2022-11-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0017_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.URLField(blank=True, default='https://cdn.acwing.com/media/user/profile/photo/103_lg_e42c28e088..jpg', max_length=256, null=True),
        ),
    ]
