# Generated by Django 3.2.8 on 2022-11-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0022_alter_player_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.URLField(default='https://cdn.acwing.com/media/user/profile/photo/29231_lg_3e166b549d.jpg', max_length=256),
        ),
    ]
