# Generated by Django 3.2.8 on 2022-11-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0023_alter_player_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='desp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='job',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
