# Generated by Django 3.2.8 on 2022-11-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0024_auto_20221115_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cpp_code_compile_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='cpp_code_compile_success_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='java_code_compile_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='java_code_compile_success_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='py_code_compile_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='py_code_compile_success_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
