# Generated by Django 3.2.8 on 2022-11-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0029_alter_platformdata_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
