# Generated by Django 3.2.8 on 2022-09-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='a_is_robot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='b_is_robot',
            field=models.BooleanField(default=False),
        ),
    ]
