# Generated by Django 3.2.8 on 2022-09-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_auto_20220912_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='a_language',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='b_language',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
