version: "3.7"
services:
  backend:
    container_name: ai_game_backend
    build:
      dockerfile: ./ai_game_backend_code/dockerfile
    ports:
      - 20010:22
      - 80:80
      - 443:443
      - 20012:15672
    volumes:
      - /home/zzq/ai_game/ai_game_backend_code:/code
      - /home/zzq/ai_game/ai_game_web_code:/code/web_code
      - /home/zzq/ai_game/conf/cert:/etc/nginx/cert
      - /home/zzq/ai_game/conf/nginx.conf:/etc/nginx/nginx.conf
      - /home/zzq/ai_game/conf/redis.conf:/etc/redis/redis.con
      - /home/zzq/ai_game/db_data/redis:/data
      - /home/zzq/ai_game/db_data/sqlite/db.sqlite3:/code/db.sqlite3
    environment:
      - TZ=Asia/Shanghai
    networks:
      - inside
    links:
      - "code_runner:runner"
  code_runner:
    container_name: ai_game_code_runner
    build:
      dockerfile: ./ai_game_coderunner_code/dockerfile
    ports:
      - 20011:22
    volumes:
      - /home/zzq/ai_game/ai_game_coderunner_code/src:/code
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    environment:
      - TZ=Asia/Shanghai
    privileged: true
    networks:
      - inside

networks:
  inside:
