version: "3.7"
services:
  backend:
    build:
      dockerfile: ./ai_game_backend_code/dockerfile
    ports:
      - 20010:22
      - 80:80
      - 443:443
      - 20013:5672
      - 20014:15672
    volumes:
      - /home/zzq/ai_game/ai_game_backend_code:/code
      - /home/zzq/ai_game/ai_game_web_code:/code/web_code
      - /home/zzq/ai_game/conf/cert:/etc/nginx/cert
      - /home/zzq/ai_game/conf/nginx.conf:/etc/nginx/nginx.conf
      - /home/zzq/ai_game/conf/redis.conf:/etc/redis/redis.conf
      - ai_game_redis:/data
    networks:
      - inside
    environment:
      - TZ=Asia/Shanghai
  code_runner:
    build:
      dockerfile: ./ai_game_coderunner_code/dockerfile
    ports:
      - 20011:22
      - 20012:9090
    volumes:
      - /home/zzq/ai_game/ai_game_coderunner_code/src:/code
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    environment:
      - TZ=Asia/Shanghai
    privileged: true
    networks:
      - inside

volumes:
  ai_game_redis:

networks:
  inside:
