# Generated by Django 3.2.8 on 2022-08-06 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20220806_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='game',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='user',
        ),
    ]
