# Generated by Django 3.2.8 on 2022-08-06 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('player', '0004_auto_20220806_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_bot', to='game.game'),
        ),
        migrations.AddField(
            model_name='bot',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_bot', to=settings.AUTH_USER_MODEL),
        ),
    ]
