# Generated by Django 3.2.8 on 2022-09-11 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0008_player_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='token',
        ),
    ]
