# Generated by Django 3.2.8 on 2022-11-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0025_auto_20221122_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('register_cnt', models.IntegerField(default=0)),
                ('login_cnt', models.IntegerField(default=0)),
            ],
        ),
    ]
