/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "code_running_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace code_running_service {


Bot::~Bot() noexcept {
}


void Bot::__set_userId(const int32_t val) {
  this->userId = val;
}

void Bot::__set_botCode(const std::string& val) {
  this->botCode = val;
}

void Bot::__set_input(const std::string& val) {
  this->input = val;
}
std::ostream& operator<<(std::ostream& out, const Bot& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t Bot::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->userId);
          this->__isset.userId = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->botCode);
          this->__isset.botCode = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->input);
          this->__isset.input = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t Bot::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("Bot");

  xfer += oprot->writeFieldBegin("userId", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->userId);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("botCode", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->botCode);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("input", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->input);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(Bot &a, Bot &b) {
  using ::std::swap;
  swap(a.userId, b.userId);
  swap(a.botCode, b.botCode);
  swap(a.input, b.input);
  swap(a.__isset, b.__isset);
}

Bot::Bot(const Bot& other0) {
  userId = other0.userId;
  botCode = other0.botCode;
  input = other0.input;
  __isset = other0.__isset;
}
Bot& Bot::operator=(const Bot& other1) {
  userId = other1.userId;
  botCode = other1.botCode;
  input = other1.input;
  __isset = other1.__isset;
  return *this;
}
void Bot::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "Bot(";
  out << "userId=" << to_string(userId);
  out << ", " << "botCode=" << to_string(botCode);
  out << ", " << "input=" << to_string(input);
  out << ")";
}

} // namespace
