/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef CodeRunning_H
#define CodeRunning_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "code_running_types.h"

namespace code_running_service {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class CodeRunningIf {
 public:
  virtual ~CodeRunningIf() {}
  virtual int32_t add_bot_code(const Bot& bot, const std::string& info) = 0;
};

class CodeRunningIfFactory {
 public:
  typedef CodeRunningIf Handler;

  virtual ~CodeRunningIfFactory() {}

  virtual CodeRunningIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(CodeRunningIf* /* handler */) = 0;
  };

class CodeRunningIfSingletonFactory : virtual public CodeRunningIfFactory {
 public:
  CodeRunningIfSingletonFactory(const ::std::shared_ptr<CodeRunningIf>& iface) : iface_(iface) {}
  virtual ~CodeRunningIfSingletonFactory() {}

  virtual CodeRunningIf* getHandler(const ::apache::thrift::TConnectionInfo&) override {
    return iface_.get();
  }
  virtual void releaseHandler(CodeRunningIf* /* handler */) override {}

 protected:
  ::std::shared_ptr<CodeRunningIf> iface_;
};

class CodeRunningNull : virtual public CodeRunningIf {
 public:
  virtual ~CodeRunningNull() {}
  int32_t add_bot_code(const Bot& /* bot */, const std::string& /* info */) override {
    int32_t _return = 0;
    return _return;
  }
};

typedef struct _CodeRunning_add_bot_code_args__isset {
  _CodeRunning_add_bot_code_args__isset() : bot(false), info(false) {}
  bool bot :1;
  bool info :1;
} _CodeRunning_add_bot_code_args__isset;

class CodeRunning_add_bot_code_args {
 public:

  CodeRunning_add_bot_code_args(const CodeRunning_add_bot_code_args&);
  CodeRunning_add_bot_code_args& operator=(const CodeRunning_add_bot_code_args&);
  CodeRunning_add_bot_code_args() noexcept
                                : info() {
  }

  virtual ~CodeRunning_add_bot_code_args() noexcept;
  Bot bot;
  std::string info;

  _CodeRunning_add_bot_code_args__isset __isset;

  void __set_bot(const Bot& val);

  void __set_info(const std::string& val);

  bool operator == (const CodeRunning_add_bot_code_args & rhs) const
  {
    if (!(bot == rhs.bot))
      return false;
    if (!(info == rhs.info))
      return false;
    return true;
  }
  bool operator != (const CodeRunning_add_bot_code_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CodeRunning_add_bot_code_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class CodeRunning_add_bot_code_pargs {
 public:


  virtual ~CodeRunning_add_bot_code_pargs() noexcept;
  const Bot* bot;
  const std::string* info;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _CodeRunning_add_bot_code_result__isset {
  _CodeRunning_add_bot_code_result__isset() : success(false) {}
  bool success :1;
} _CodeRunning_add_bot_code_result__isset;

class CodeRunning_add_bot_code_result {
 public:

  CodeRunning_add_bot_code_result(const CodeRunning_add_bot_code_result&) noexcept;
  CodeRunning_add_bot_code_result& operator=(const CodeRunning_add_bot_code_result&) noexcept;
  CodeRunning_add_bot_code_result() noexcept
                                  : success(0) {
  }

  virtual ~CodeRunning_add_bot_code_result() noexcept;
  int32_t success;

  _CodeRunning_add_bot_code_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const CodeRunning_add_bot_code_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const CodeRunning_add_bot_code_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CodeRunning_add_bot_code_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _CodeRunning_add_bot_code_presult__isset {
  _CodeRunning_add_bot_code_presult__isset() : success(false) {}
  bool success :1;
} _CodeRunning_add_bot_code_presult__isset;

class CodeRunning_add_bot_code_presult {
 public:


  virtual ~CodeRunning_add_bot_code_presult() noexcept;
  int32_t* success;

  _CodeRunning_add_bot_code_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class CodeRunningClient : virtual public CodeRunningIf {
 public:
  CodeRunningClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  CodeRunningClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  int32_t add_bot_code(const Bot& bot, const std::string& info) override;
  void send_add_bot_code(const Bot& bot, const std::string& info);
  int32_t recv_add_bot_code();
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class CodeRunningProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<CodeRunningIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext) override;
 private:
  typedef  void (CodeRunningProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_add_bot_code(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  CodeRunningProcessor(::std::shared_ptr<CodeRunningIf> iface) :
    iface_(iface) {
    processMap_["add_bot_code"] = &CodeRunningProcessor::process_add_bot_code;
  }

  virtual ~CodeRunningProcessor() {}
};

class CodeRunningProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  CodeRunningProcessorFactory(const ::std::shared_ptr< CodeRunningIfFactory >& handlerFactory) noexcept :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo) override;

 protected:
  ::std::shared_ptr< CodeRunningIfFactory > handlerFactory_;
};

class CodeRunningMultiface : virtual public CodeRunningIf {
 public:
  CodeRunningMultiface(std::vector<std::shared_ptr<CodeRunningIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~CodeRunningMultiface() {}
 protected:
  std::vector<std::shared_ptr<CodeRunningIf> > ifaces_;
  CodeRunningMultiface() {}
  void add(::std::shared_ptr<CodeRunningIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  int32_t add_bot_code(const Bot& bot, const std::string& info) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->add_bot_code(bot, info);
    }
    return ifaces_[i]->add_bot_code(bot, info);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class CodeRunningConcurrentClient : virtual public CodeRunningIf {
 public:
  CodeRunningConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  CodeRunningConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  int32_t add_bot_code(const Bot& bot, const std::string& info) override;
  int32_t send_add_bot_code(const Bot& bot, const std::string& info);
  int32_t recv_add_bot_code(const int32_t seqid);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

} // namespace

#endif
