/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Message_H
#define Message_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "message_types.h"



#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class MessageIf {
 public:
  virtual ~MessageIf() {}
  virtual int32_t response(const std::string& info) = 0;
};

class MessageIfFactory {
 public:
  typedef MessageIf Handler;

  virtual ~MessageIfFactory() {}

  virtual MessageIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(MessageIf* /* handler */) = 0;
  };

class MessageIfSingletonFactory : virtual public MessageIfFactory {
 public:
  MessageIfSingletonFactory(const ::std::shared_ptr<MessageIf>& iface) : iface_(iface) {}
  virtual ~MessageIfSingletonFactory() {}

  virtual MessageIf* getHandler(const ::apache::thrift::TConnectionInfo&) override {
    return iface_.get();
  }
  virtual void releaseHandler(MessageIf* /* handler */) override {}

 protected:
  ::std::shared_ptr<MessageIf> iface_;
};

class MessageNull : virtual public MessageIf {
 public:
  virtual ~MessageNull() {}
  int32_t response(const std::string& /* info */) override {
    int32_t _return = 0;
    return _return;
  }
};

typedef struct _Message_response_args__isset {
  _Message_response_args__isset() : info(false) {}
  bool info :1;
} _Message_response_args__isset;

class Message_response_args {
 public:

  Message_response_args(const Message_response_args&);
  Message_response_args& operator=(const Message_response_args&);
  Message_response_args() noexcept
                        : info() {
  }

  virtual ~Message_response_args() noexcept;
  std::string info;

  _Message_response_args__isset __isset;

  void __set_info(const std::string& val);

  bool operator == (const Message_response_args & rhs) const
  {
    if (!(info == rhs.info))
      return false;
    return true;
  }
  bool operator != (const Message_response_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Message_response_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Message_response_pargs {
 public:


  virtual ~Message_response_pargs() noexcept;
  const std::string* info;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Message_response_result__isset {
  _Message_response_result__isset() : success(false) {}
  bool success :1;
} _Message_response_result__isset;

class Message_response_result {
 public:

  Message_response_result(const Message_response_result&) noexcept;
  Message_response_result& operator=(const Message_response_result&) noexcept;
  Message_response_result() noexcept
                          : success(0) {
  }

  virtual ~Message_response_result() noexcept;
  int32_t success;

  _Message_response_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const Message_response_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Message_response_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Message_response_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Message_response_presult__isset {
  _Message_response_presult__isset() : success(false) {}
  bool success :1;
} _Message_response_presult__isset;

class Message_response_presult {
 public:


  virtual ~Message_response_presult() noexcept;
  int32_t* success;

  _Message_response_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class MessageClient : virtual public MessageIf {
 public:
  MessageClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  MessageClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  int32_t response(const std::string& info) override;
  void send_response(const std::string& info);
  int32_t recv_response();
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class MessageProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<MessageIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext) override;
 private:
  typedef  void (MessageProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_response(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  MessageProcessor(::std::shared_ptr<MessageIf> iface) :
    iface_(iface) {
    processMap_["response"] = &MessageProcessor::process_response;
  }

  virtual ~MessageProcessor() {}
};

class MessageProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  MessageProcessorFactory(const ::std::shared_ptr< MessageIfFactory >& handlerFactory) noexcept :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo) override;

 protected:
  ::std::shared_ptr< MessageIfFactory > handlerFactory_;
};

class MessageMultiface : virtual public MessageIf {
 public:
  MessageMultiface(std::vector<std::shared_ptr<MessageIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~MessageMultiface() {}
 protected:
  std::vector<std::shared_ptr<MessageIf> > ifaces_;
  MessageMultiface() {}
  void add(::std::shared_ptr<MessageIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  int32_t response(const std::string& info) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->response(info);
    }
    return ifaces_[i]->response(info);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class MessageConcurrentClient : virtual public MessageIf {
 public:
  MessageConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  MessageConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  int32_t response(const std::string& info) override;
  int32_t send_response(const std::string& info);
  int32_t recv_response(const int32_t seqid);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif



#endif
