# Generated by Django 3.2.8 on 2022-11-09 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_voice', '0008_freshnews_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freshnews',
            name='players',
        ),
    ]
