# Generated by Django 3.2.8 on 2022-11-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_voice', '0010_player_like_fresh_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='freshnews',
            name='forward_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='freshnews',
            name='forwarded_id',
            field=models.IntegerField(default=-1),
        ),
    ]
