# Generated by Django 3.2.8 on 2022-09-29 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0013_alter_player_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreshNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=5000)),
                ('imgs', models.TextField(max_length=5000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_freshnews', to='player.player')),
            ],
        ),
    ]
