# Generated by Django 3.2.8 on 2022-09-29 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_voice', '0002_auto_20220929_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freshnews',
            name='imgs',
        ),
    ]
