# Generated by Django 3.2.8 on 2022-11-09 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('player_voice', '0009_remove_freshnews_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player_Like_Fresh_News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freshNews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_voice.freshnews')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
