# 镜像
FROM zzq10/ubuntu:python
# 镜像制作人信息
MAINTAINER zzq "17687952609@163.com"
# 设置时区
# ENV TIME_ZONE Asia/Shanghai
RUN apt-get update \
        && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata \
        && ln -snf /usr/share/zoneinfo/$TIME_ZONE /etc/localtime && echo $TIME_ZONE > /etc/timezone \
        && dpkg-reconfigure -f noninteractive tzdata \
        && apt-get clean \
        && rm -rf /tmp/* /var/cache/* /usr/share/doc/* /usr/share/man/* /var/lib/apt/lists/
# 配置pip源
RUN mkdir ~/.pip
RUN echo "[global] \n\
index-url = https://pypi.tuna.tsinghua.edu.cn/simple" > ~/.pip/pip.conf
# 创建父级目录
RUN mkdir /code
WORKDIR /code
# 安装python依赖包
COPY ./conf/ai_game_coderunner_requirements.txt ./requirements.txt
RUN pip3 install -r requirements.txt
# 代码复制到容器里
COPY ./ai_game_coderunner_code/src .
# 运行项目
RUN chmod +x ./scripts/start.sh
CMD sh ./scripts/start.sh
