# Generated by Django 3.2.8 on 2022-10-21 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_auto_20220926_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='a_sx',
        ),
        migrations.RemoveField(
            model_name='record',
            name='a_sy',
        ),
        migrations.RemoveField(
            model_name='record',
            name='b_sx',
        ),
        migrations.RemoveField(
            model_name='record',
            name='b_sy',
        ),
    ]
